sip:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100
        
    arm_controller:
      type: position_controllers/JointTrajectoryController
      joints:
         - base_link1_joint
         - link1_link2_joint
         - link2_link3_joint
         - link3_link4_joint
         
    
    gripper_controller:
      type: position_controllers/JointTrajectoryController
      joints:
         - l_finger_joint
         - r_finger_joint  
         - link4_link5_joint 

    
      constraints:
          goal_time: 0.6
          stopped_velocity_tolerance: 0.05
          base_link1_joint: {trajectory: 0.1, goal: 0.1}
          link1_link2_joint: {trajectory: 0.1, goal: 0.1}
          link2_link3_joint: {trajectory: 0.1, goal: 0.1}
          link3_link4_joint: {trajectory: 0.1, goal: 0.1}
          l_finger_joint: {trajectory: 0.1, goal: 0.1}
          r_finger_joint: {trajectory: 0.1, goal: 0.1}
          
          
      stop_trajectory_duration: 0.5
      state_publish_rate:  25
      action_monitor_rate: 10
      
    

